config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'photos#index'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/faq'
  resources :photos
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

   validates :title, presence: true, length: { maximum: 50}, uniqueness: true
   validates :caption, presence: true, length: { maximum: 300}, uniqueness: true
   validates :avatar, presence: true
   
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
 has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def about
    end
    
    def contact
    end
    
    def faq
    end
    
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :authenticate_user!, only: [:edit, :update, :destroy]
    
    def index
       @photos = Photo.all
    end
    
    def show
       @photo = Photo.find(params[:id])
    end
    
    def new
       @photo = current_user.photos.build
    end
    
    def edit
       @photo = Photo.find(params[:id])
    end
    
    def create
        @photo = current_user.photos.build(photo_params)
       
       if @photo.save
           redirect_to @photo
           flash[:success] = "写真の作成に成功しました"
       else
           render 'new'
       end
    end
    
    def update
        @photo = Photo.find(params[:id])
        
        if @photo.update(photo_params
        )
        redirect_to @photo
        else
            render 'edit'
        end
    end
    
    def destroy
       @photo = Photo.find(params[:id])
       @photo.destroy
       flash[:success] = "写真の削除に成功しました"
       redirect_to photos_path
    end
    
    private 
       def photo_params
           params.require(:photo).permit(:title, :caption, :avatar)
       end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns the full title on a per-page basis.
   def full_title(page_title = '')
      base_title = "Photo App"
         if page_title.empty?
          base_title
         else
          page_title + " | " + base_title
         end
   end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_alert.html.erb
<div class="alert-bar">
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       </div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
    <ul>
    <li><%= link_to "About",  pages_about_path  %></li>
    <li><%= link_to "Contact", pages_contact_path  %></li>
    <li><%= link_to "FAQ", pages_faq_path  %></li>
     
    </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top  navbar-inverse">
    <div class="container">
    <%= link_to "Photo App", root_path, id: "logo"%>    
     
    <nav> 
    <ul class="nav navbar-nav navbar-right">
      
      
      <% if user_signed_in? %>
      
      
          
          <li><%= link_to 'ユーザー情報の編集', edit_user_registration_path   %></li>
      
      
      <li><%= link_to '新規作成', new_photo_path %></li>
      
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
       <li><%= link_to 'ログイン', new_user_session_path%></li>
      
      <% end %>
      
      <li><%= link_to 'サインアップ', new_user_registration_path%></li>
      
      
    </div>
    </ul>
    </nav> 
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  <%= render 'layouts/shim' %>
  </head>

  <body>
    
    
    <%= render 'layouts/header' %>
    
    <div class="container main-wrapper">
       <div class="message-wrapper">
          <% flash.each do |message_type, message|%>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
       </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <h3>このサイトについて</h3>
    
    <div class="container center-jumbotoron">
        <div class="row">
            <div class="col">
                <p>このサイトは写真の投稿を自由にできるサイトです。</p>
            </div>
            
        </div>
        
    </div>
    
    <%= link_to 'トップページに戻る', photos_path, class: "btn btn-outline-primary" %>
</div>

app/views/pages/contact.html.erb
<div class="container">
    <h3>お問い合わせ</h3>
    
    <div class="container center-jumbotoron">
        <div class="row">
            <div class="col">
                <p>お問い合わせはこちらのメールアドレスにお願いします。</p><br>
                <p>example@example.com</p>
            </div>
            
        </div>
        
    </div>
    
    <%= link_to 'トップページに戻る', photos_path, class: "btn btn-outline-primary" %>
</div>

app/views/pages/faq.html.erb
<div class="container">
    <h3>FAQ</h3>
    
    <div class="container jumbotoron">
        

<button class="accordion">登録はどうすればいいいですか？</button>
<div class="panel">
  <p>初めてご利用の方は<%= link_to "サインアップ", new_user_registration_path(@user) %>
よりご登録をお願いします。既にアカウントをお持ちの方は<%= link_to "ログイン", new_user_session_path(@user) %>よりログインをお願いします</p>
</div>



<button class="accordion">パスワードを忘れてしまいました。どうすればいいですか？</button>
<div class="panel">
  <p><%= link_to "パスワードの変更", new_user_password_path(@user) %>よりパスワードの再登録をお願いします</p>
</div>


<button class="accordion">無料で利用できますか？</button>
<div class="panel">
  <p>はいすべて無料で利用できます</p>
</div>
        
    </div>
    
    <%= link_to 'トップページに戻る', photos_path, class: "btn btn-outline-primary" %>
    
</div>

app/views/photos/edit.html.erb
<% provide(:title, "編集") %>
<h3>画像の編集</h3>
<div class="container ">



     <%= form_for @photo, url: photo_path, html: { multipart: true } do |form| %>
       <div class="field">
       <%= form.label 'タイトル' %>
       <%= form.text_field :title %>
       </div>
       
       <div class="field">
       <%= form.label '画像の設定' %>
       <%= form.file_field :avatar %>
       </div>
       
       <div class="field">
       <%= form.label '画像の説明' %>
       <%= form.text_field :caption %><br>
       </div>
       
       <div class="actions">
       <%= form.submit "画像を作成", class: "btn btn-primary"  %>
       </div>
       
     <% end %>
     
     

<%= link_to '戻る', photos_path, class: "btn btn-outline-primary" %>
</div>

app/views/photos/index.html.erb
<% provide(:title, "ギャラリー") %>

<div class="container">
<h3>ギャラリー</h3>

<div class="container">
    
<div class="row">
    <% @photos.each do |photo| %>
    
    <div class=" col-xs-12 col-sm-6 col-md-4 col-lg-3">
     
     
     
     <div class="container photo-container"><a href="/photos/<%= photo.id %>">
     <%= image_tag photo.avatar.url(:medium), class:"photo" %>
     </a></div><br>
     
     <div class="btn-group">
 <% if user_signed_in? %>
     
    <%= link_to '編集' , edit_photo_path(photo), class: "btn btn-outline-primary"%>
    <%= link_to '削除', photo_path(photo), method: :delete, data: {confirm: '本当に削除してもよろしいですか？'},class: "btn btn-outline-primary" %>
 <% end %>
 <%= link_to '表示' , photo_path(photo), class: "btn btn-outline-primary" %>
     </div>
     
    </div>
    
    <% end %>
   </div> 
   
<% if user_signed_in? %>
   <%= link_to '新規作成', new_photo_path, class: "btn btn-primary" %>
<% end %>
</div>

</div>

app/views/photos/new.html.erb
<% provide(:title, "新規作成") %>


<div class="row">
<h3>新規作成</h3>
</div>

<div class="row">
<div class="container ">




     <%= form_for @photo, url: photos_path, html: { multipart: true } do |form| %>
       
       <div class="field">
       <%= form.label 'タイトル' %><br>
       <%= form.text_field :title %>
       </div>
       
       <div class="field">
       <%= form.label '画像の設定' %><br>
       <%= form.file_field :avatar %>
       </div>
       
       <div class="field">
       <%= form.label '画像の説明' %><br>
       <%= form.text_field :caption %>
       </div>
       
       
       
       <div class="actions">
       <%= form.submit "画像を作成", class: "btn btn-primary"%>
       </div>
       
     <% end %>
     
   </div>
   </div>
   
   <div class="row">
<%= link_to '戻る', photos_path, class: "btn btn-outline-primary" %>

  </div>

app/views/photos/show.html.erb
<% provide(:title, "画像の詳細") %>
<h3>画像の詳細</h3>
<div class="container">
    
    <div class="row">
    <%= @photo.title %></div><br>
    
    <div class="row">
    <%= image_tag @photo.avatar.url(:medium) %></div><br>
    <div class="row">
    <%= @photo.caption %></div><br>
    
    <%= @photo.user_id %>
  
<div class="row">
    <div class="btn-group">
<% if user_signed_in? %>
<%= link_to '編集', edit_photo_path, class: "btn btn-outline-primary" %>
<%= link_to '削除', photo_path(@photo), method: :delete, data: {confirm: '本当に削除してもよろしいですか？'},class: "btn btn-outline-primary" %>

<% end %>
<%= link_to '戻る', photos_path, class: "btn btn-outline-primary" %>
    </div>
</div>

</div>
    
    